[[plugins]]
repo = 'Shougo/dein.vim'

# ====================
# 見た目周り
# ====================
# テーマ
[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'
hook_add = '''
    set t_Co=256
    set background=dark
    syntax on
    colorscheme hybrid_reverse '''

# パワーライン
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline_powerline_fonts = 0
let g:airline#extensions#tabline#enabled = 1
let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])
let g:airline#extensions#hunks#enabled = 0
'''

# パワーラインのテーマ
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme='papercolor'
  let g:airline#extensions#ale#enabled = 1
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_start_level = 2
  let g:indent_guides_guide_size = 1
  let g:indent_guides_exclude_filetypes = ['help', 'nerdtree', 'tagbar', 'unite']
'''

# =-=-=-=-=-=-=-=-=-=-=
# 大事なやつ
# =-=-=-=-=-=-=-=-=-=-=
# 非同期処理を実現してくれるやつ
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# 非同期補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
    \ neosnippet#expandable_or_jumpable() ?
    \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
hook_add = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

# htmlタグ補完
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
  let g:user_emmet_leader_key='<C-Q>'
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_warning = '**'
  let g:LanguageClient_serverCommands = {
      \ 'vue': ['vls'],
      \ }
  let g:ale_fixers = {
      \ 'javascript': ['eslint'],
      \ }
  let g:ale_sign_column_always = 1
  let g:ale_lint_on_enter = 0
  let g:ale_open_list = 1
  let g:ale_keep_list_window_open = 0
'''

# ====================
# ファイル操作周り
# ====================
# ファイルツリーのやつ
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <silent><C-e> :NERDTreeToggle<CR>
    nmap <Leader><Tab> <C-w>w
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

# ====================
# Git関連
# ====================
[[plugins]]
repo = 'airblade/vim-gitgutter'
    
