################################################
# All Files
################################################
[[plugins]]
repo = 'majutsushi/tagbar'
hook_post_source = '''
    let g:tagbar_width = 30
    let g:tagbar_autoshowtag = 1
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

# 暗黒の力
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_event = 'BufRead'
hook_post_source = '''
call denite#custom#var('file_rec', 'command',
\ ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
call denite#custom#var('grep', 'command',
\ ['pt', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
call denite#custom#var('grep', 'default_opts', [])
call denite#custom#var('grep', 'recursive_opts', [])
'''

