################################################
# Other Files
################################################

[[plugins]] # markdownのシンタックス
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]] # markdownのtableの整形
repo = 'godlygeek/tabular'
on_ft = ['markdown', 'mkd']

[[plugins]] # markdownのクゥオート内シンタックス
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown', 'mkd']

[[plugins]] # markdownのPreview
repo = 'kannokanno/previm'
on_ft = ['markdown', 'mkd']

[[plugins]] # ブラウザ起動
repo = 'tyru/open-browser.vim'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_ft = ['markdown', 'mkd']
hook_add = '''
  au FileType markdown vmap <Bslash><Bslash> :EasyAlign*<Bar><Enter>
'''

[[plugins]] # tomlのシンタックス
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # jsonのシンタックス
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

[[plugins]] # 直接DB触ったりSQL補完したり
repo = 'vim-scripts/dbext.vim'
on_ft = 'sql'
