########################################
# python
########################################

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_post_source = '''
  let g:deoplete#sources#jedi#show_docstring = 0
'''

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
on_ft = 'python'
hook_post_source = '''
    let g:gen_tags#ctags_auto_gen = 1
    let g:gen_tags#gtags_auto_gen = 1
'''
