tap "homebrew/bundle"
tap "homebrew/core"

brew "ansible"
brew "ansible-lint"
brew "gh"
brew "jq"
brew "wget"
brew "mas"
brew "minio"
brew "mysql@5.7"
brew "redis"
brew "direnv"
brew "shared-mime-info"
brew "ag"

cask "google-japanese-ime"
cask "font-hack-nerd-font"
