[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme='hybrid'
let g:airline#extensions#ale#enabled = 1
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1
'''

# [[plugins]] # FileTree
# repo = 'scrooloose/nerdtree'
# hook_add = '''
# nnoremap <silent><C-e> :NERDTreeToggle<CR>
# nmap <Leader><Tab> <C-w>w
# autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
# '''

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons', 'defx-git']
hook_add = '''
source ~/.config/nvim/plugins/defx.rc.vim
call defx#custom#option('_', {
  \ 'winwidth': 30,
  \ 'split': 'vertical',
  \ 'direction': 'topleft',
  \ 'show_ignored_files': 1,
  \ 'buffer_name': 'explorer',
  \ 'toggle': 1,
  \ 'resume': 1,
  \ 'columns': 'indent:icons:filename:type'
  \ })
"""
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
  let g:user_emmet_leader_key='<C-Q>'
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = "leafgarland/typescript-vim"

[[plugins]]
repo = "Quramy/tsuquyomi"

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
